# https://pub.dev/packages/yumemi_lints
include: package:yumemi_lints/flutter/3.16.0/recommended.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_use_of_visible_for_testing_member: error
