targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          include:
            - lib/**/provider/*.dart
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
      json_serializable:
        options:
          field_rename: snake
          checked: true
        generate_for:
          include:
            - lib/features/weather/model/*.dart
      freezed:
        generate_for:
          include:
            - lib/features/weather/model/*.dart
